[workspace]
resolver = "2"
members = [
    "crates/snake-core",
    "crates/snake-app",
    "crates/snake-train",
    "crates/snake-server",
    "crates/snake-py",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"

[profile.release]
opt-level = 2

# Optimize WASM size a bit without hurting build times too much.
[profile.release.package."*"]
opt-level = 2
