[package]
name = "snake-app"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
snake-core = { path = "../snake-core", features = ["serde"] }
eframe = { version = "0.34", features = ["persistence"] }
log = "0.4"
serde = { version = "1", features = ["derive"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.11"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4"

[dev-dependencies]
egui_kittest = { version = "0.34.3", features = ["snapshot", "wgpu"] }
